# Generated by Django 5.0.4 on 2026-03-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaImportanteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('funcion_clave', 'Función clave'), ('no_tocar', 'No tocar'), ('decision_arquitectura', 'Decisión de arquitectura'), ('riesgo', 'Riesgo conocido')], max_length=30)),
                ('titulo', models.CharField(max_length=300)),
                ('contenido_markdown', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_importantes', to='projects.proyectowiki')),
            ],
            options={
                'verbose_name': 'Nota Importante',
                'ordering': [models.Case(models.When(prioridad='alta', then=0), models.When(prioridad='media', then=1), models.When(prioridad='baja', then=2), default=3, output_field=models.IntegerField()), '-fecha_actualizacion'],
            },
        ),
    ]
