# Generated by Django 5.0.4 on 2026-03-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionGitHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='github', max_length=20)),
                ('owner_repo', models.CharField(max_length=200)),
                ('repo_url', models.URLField()),
                ('sync_activa', models.BooleanField(default=True)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracion_github', to='projects.proyectowiki')),
            ],
            options={
                'verbose_name': 'Integración GitHub',
            },
        ),
        migrations.CreateModel(
            name='PullRequestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('open', 'Abierta'), ('merged', 'Merged'), ('closed', 'Cerrada')], max_length=10)),
                ('rama_origen', models.CharField(max_length=200)),
                ('rama_destino', models.CharField(max_length=200)),
                ('labels', models.JSONField(default=list)),
                ('url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.proyectowiki')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'ordering': ['-updated_at'],
                'unique_together': {('proyecto', 'pr_number')},
            },
        ),
    ]
