# Generated by Django 5.0.4 on 2026-03-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320)),
                ('contenido_markdown', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('version_actual', models.PositiveIntegerField(default=1)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='projects.proyectowiki')),
                ('ultima_edicion_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Página Wiki',
                'verbose_name_plural': 'Páginas Wiki',
                'ordering': ['titulo'],
                'unique_together': {('proyecto', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VersionPaginaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('contenido_markdown', models.TextField()),
                ('mensaje_cambio', models.CharField(blank=True, max_length=500)),
                ('fecha_edicion', models.DateTimeField(auto_now_add=True)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_editadas', to=settings.AUTH_USER_MODEL)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='pages.paginawiki')),
            ],
            options={
                'verbose_name': 'Versión de Página',
                'verbose_name_plural': 'Versiones de Página',
                'ordering': ['-numero_version'],
                'unique_together': {('pagina', 'numero_version')},
            },
        ),
    ]
